// All portal imagery. To swap in the client's own photographs:
//   1. replace the source path in scripts/prepare-images.py
//   2. run `python3 scripts/prepare-images.py`
// Nothing in this file needs to change unless a slug is added or removed.

import { manifest } from './image-manifest.js'

const BASE = '/images'

export function srcSet(slug) {
  // The manifest is generated by scripts/prepare-images.py and lists only the
  // widths that were actually written. Never hardcode widths here: the
  // forestry sources are 960px wide and cannot produce the larger sizes.
  const widths = manifest[slug]
  if (!widths) throw new Error(`unknown image slug: ${slug}`)
  return {
    src: `${BASE}/${slug}-${widths[widths.length - 1]}.webp`,
    srcSet: widths.map((w) => `${BASE}/${slug}-${w}.webp ${w}w`).join(', '),
    lqip: `${BASE}/${slug}-lqip.webp`,
  }
}

// Hero Ken Burns rotation, in order.
export const heroSlugs = ['hero-1', 'hero-2', 'hero-3']

export const heroAlt = {
  'hero-1': 'Wetlands and open sky across a Rwandan valley',
  'hero-2': 'A misty lake with a rocky island in the foreground',
  'hero-3': 'A young mountain gorilla in dense forest foliage',
}

export const logo = `${BASE}/logo-rsa.png`

// Unused alternates, kept for the client to swap in:
//   conservation5, tourism2, water resource2, water resource3,
//   forestry-bridge, forest1-3
